//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсач_КМиСОИБИ.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("курсач_КМиСОИБИ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 04	14	05	07	06	04	13	01
        ///10	11	08	13	12	11	11	15
        ///09	04	01	10	07	10	04	13
        ///02	12	13	01	01	00	01	00
        ///13	06	10	00	05	07	03	05
        ///08	13	03	08	15	02	15	07
        ///00	15	04	09	13	01	05	10
        ///14	10	02	15	08	13	09	04
        ///06	02	14	14	04	03	00	09
        ///11	03	15	04	10	06	10	02
        ///01	08	12	06	09	08	14	03
        ///12	01	07	12	14	05	07	14
        ///07	00	06	11	00	09	06	06
        ///15	07	00	02	03	12	08	11
        ///05	05	09	05	11	15	02	08
        ///03	09	11	03	02	14	12	12.
        /// </summary>
        internal static string S_блоки {
            get {
                return ResourceManager.GetString("S_блоки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 	14 	4 	13 	1 	2 	15 	11 	8 	3 	10 	6 	12 	5 	9 	0 	7
        ///1 	0 	15 	7 	4 	14 	2 	13 	1 	10 	6 	12 	11 	9 	5 	3 	8
        ///2 	4 	1 	14 	8 	13 	6 	2 	11 	15 	12 	9 	7 	3 	10 	5 	0
        ///3 	15 	12 	8 	2 	4 	9 	1 	7 	5 	11 	3 	14 	10 	0 	6 	13.
        /// </summary>
        internal static string Преобразования_S1 {
            get {
                return ResourceManager.GetString("Преобразования_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S2 {
            get {
                return ResourceManager.GetString("Преобразования_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S3 {
            get {
                return ResourceManager.GetString("Преобразования_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S4 {
            get {
                return ResourceManager.GetString("Преобразования_S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S5 {
            get {
                return ResourceManager.GetString("Преобразования_S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S6 {
            get {
                return ResourceManager.GetString("Преобразования_S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S7 {
            get {
                return ResourceManager.GetString("Преобразования_S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Преобразования_S8 {
            get {
                return ResourceManager.GetString("Преобразования_S8", resourceCulture);
            }
        }
    }
}
